### PR TITLE
Update compileSdkVersion to fix Android release build

### LINKED ISSUE #96: Android release build fails, need to bump compileSdkVersion
### Steps to Reproduce

1. Create empty flutter app
2. Run in release mode, it runs
3. Add isar community to pubspec as per the readme
4. Run in release mode, it fails with the following error:
```
Execution failed for task ':isar_flutter_libs:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:C:\Dev\flutter_application_1\build\isar_flutter_libs\intermediates\merged_res\release\values\values.xml:194: AAPT: error: resource android:attr/lStar not found.
```

### Details

 - Platform: Building in release for Android on Windows
 - Flutter version: 3.24.0
 - Isar version: 3.1.7

### Possible solution

Should be fixed if the `compileSdkVersion` in `isar_flutter_libs` is set to 31 or higher.

### PR DESCRIPTION
**Pull request by Arko109**
Should fix #96, 34 is the version used currently by default in flutter.

### CODE REVIEW

**Review by vicenterusso — APPROVED** [review]

**Comment by Arko109** [comment]
Wait before merging, there's an issue apparently https://github.com/isar-community/isar/issues/96#issuecomment-2276177593

**Comment by vicenterusso** [comment]
> Wait before merging, there's an issue apparently [#96 (comment)](https://github.com/isar-community/isar/issues/96#issuecomment-2276177593)

I used a local package with ONLY the `compileSdkVersion` changed to 34 and it compiled. I don't believe the error is related to this PR

**Comment by Arko109** [comment]
I tried it on my production app, not the empty one and it compiles for me too, but the app is not going past the splashscreen like in the issue. So something goes wrong when isar is actually called

**Review by mrclauss — APPROVED** [review]

**Comment by mrclauss** [comment]
Did you guys find out if the issue hanging in splash screen is related to this? Should we merge this?

**Comment by vicenterusso** [comment]
> Did you guys find out if the issue hanging in splash screen is related to this? Should we merge this?

I think the error is unrelated to isar itself. Its working here

**Pull request merged**
