### PR TITLE
Adds privacy files

### PR DESCRIPTION
**Pull request by vicenterusso**
Fixes https://github.com/isar-community/isar/issues/63

### CODE REVIEW

**Review by mrclauss — APPROVED** [review]
Are you sure AccessedApi is empty? I think there is trivial stuff like fstat contained in that...

**Comment by vicenterusso** [comment]
> Are you sure AccessedApi is empty? I think there is trivial stuff like fstat contained in that...

That's a good question indeed. This is a brief description for each reason that could be listed

- **Display Disk Space Information (85F4.1)**: Allows apps to show how much disk space is available or used, potentially in specific units like bytes or time for video storage. Useful in apps that manage file storage or show system stats.

- **Check Disk Space for Functionality (E174.1)**: Used by apps to ensure there's enough space to perform operations like saving files. This can help apps decide when to stop downloads or clean up old files to prevent issues.

- **Include Disk Space in Bug Reports (7D9E.1)**: Enables apps to add disk space details in bug reports that users choose to send. This helps developers understand if disk space issues contributed to the bug.

- **Disk Space for Health Research (B728.1)**: Specific to health research apps that need to monitor disk space to ensure data collection isn't impacted by low storage.

I _might be wrong_, but I don't think that Isar does check for disk space. Maybe someone could throw some more ideas and/or suggestions?

**Comment by mrclauss** [comment]
Isar itself probably does not, but I can very well imagine that libmbdx does. So I'd propose to add (E174.1) here...

Cheers, Martin

Am 30. April 2024 17:21:08 MESZ schrieb Vicente Russo ***@***.***>:
>> Are you sure AccessedApi is empty? I think there is trivial stuff
>like fstat contained in that...
>
>That's a good question indeed. This is a brief description for each
>reason that could be listed
>
>- **Display Disk Space Information (85F4.1)**: Allows apps to show how
>much disk space is available or used, potentially in specific units
>like bytes or time for video storage. Useful in apps that manage file
>storage or show system stats.
>
>- **Check Disk Space for Functionality (E174.1)**: Used by apps to
>ensure there's enough space to perform operations like saving files.
>This can help apps decide when to stop downloads or clean up old files
>to prevent issues.
>
>- **Include Disk Space in Bug Reports (7D9E.1)**: Enables apps to add
>disk space details in bug reports that users choose to send. This helps
>developers understand if disk space issues contributed to the bug.
>
>- **Disk Space for Health Research (B728.1)**: Specific to health
>research apps that need to monitor disk space to ensure data collection
>isn't impacted by low storage.
>
>I _might be wrong_, but I don't think that Isar does check for disk
>space. Maybe someone could throw some more ideas and/or suggestions?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/isar-community/isar/pull/64#issuecomment-2085644621
>You are receiving this because your review was requested.
>
>Message ID: ***@***.***>

-- 
Martin Clauss
Meine Contactulater Card - All meine Kontaktinfo immer aktuell und vollständig:
https://contactulater.app/me/mc

**Comment by frederikstonge** [comment]
You can use this analyzer to know what is missing : https://github.com/crasowas/app_store_required_privacy_manifest_analyser/tree/main

**Pull request merged**
